Lw5 Бирюков Георгий (2)
alexander-filimonov/pp pull request #13
Opened 2017-03-16 18:37 UTC by intmpg

2017-03-21 05:30 UTC, wrager requested changes

2017-03-21 05:30 UTC, wrager commented on lw5/lw5_Biryukov(2)/ConsoleApplication21/Backer.cpp
> +std::vector<int> BackerSort(std::vector<int> & vec)
Batcher

2017-03-21 05:30 UTC, wrager commented on lw5/lw5_Biryukov(2)/ConsoleApplication21/Backer.cpp
> +	return 0;
И всё? А где ООП? Где хотя бы работающая программа? Где хотя бы запуск `BackerSort`?

2017-03-25 17:51 UTC, intmpg commented
исправил

2017-04-21 10:02 UTC, wrager approved these changes

2017-04-21 10:02 UTC, merged