Patrushev Oleg lw5 (sort)
alexander-filimonov/pp pull request #4
Opened 2017-02-15 19:43 UTC by JokerSSmile

2017-03-14 05:30 UTC, wrager requested changes
Замечания

2017-03-14 05:30 UTC, wrager commented on lw5/Patrushev_Oleg/CalculateAlgorithm.h
> +#pragma once
BatchersMergeSorter.h

2017-03-14 05:30 UTC, wrager commented on lw5/Patrushev_Oleg/ReadMe.txt
> +﻿========================================================================
ReadMe.txt убираем

2017-03-14 05:30 UTC, wrager commented on lw5/Patrushev_Oleg/CalculateLinear.h
> +	CBatchersMergeSorterLinear(const std::vector<T>& vec)
В `.h` файлах не должно быть имплементаций

2017-03-14 05:30 UTC, wrager commented on lw5/Patrushev_Oleg/CalculateAlgorithm.cpp
> +#include "CalculateAlgorithm.h"
BatchersMergeSorter.cpp

2017-03-14 05:30 UTC, wrager commented on lw5/Patrushev_Oleg/CalculateAlgorithm.cpp
> +std::vector<T> GetResultVector()
Почему методы не относятся к классу?

2017-03-21 05:09 UTC, wrager approved these changes

2017-03-21 05:09 UTC, wrager commented on lw5/Patrushev_Oleg/lab5.cpp
> +void OutputWorkTime(T& callback)
А зачем здесь шаблон?

2017-03-21 05:10 UTC, merged

2017-03-21 11:07 UTC, JokerSSmile commented on lw5/Patrushev_Oleg/lab5.cpp
> +void OutputWorkTime(T& callback)
Тут незачем, можно на std::function<void()> поменять