Bochkarev Maxim Lab1 var1
alexander-filimonov/pp pull request #7
Opened 2017-02-28 05:37 UTC by onethousandsuns

1 вариант - вычисление числа Пи методом Монте Карло

2017-03-14 06:25 UTC, wrager requested changes
Замечания

2017-03-14 06:25 UTC, wrager commented on lw5/lw5/lw5.cpp
> +bool ReadCommandLineParams(int argc, char *argv[], int& clientsCount);
`ReadCommandLineParameters`

2017-03-14 06:25 UTC, wrager commented on lw5/lw5/lw5.cpp
> +		cout << "Command line parametres read error. Run app with /? to help.\n";
`parameters`

2017-03-14 06:25 UTC, wrager commented on lw5/lw5/lw5.cpp
> +		catch (exception e) {
Ловите конкретное исключение

2017-03-14 06:25 UTC, wrager commented on lw5/lw5/MonteCarloPiCalculator.cpp
> +bool CMonteCarloPiCalculator::IsPoitnInCircle(double x, double y)
`Point`

2017-03-17 06:45 UTC, onethousandsuns commented
Замечания исправлены

2017-03-17 09:57 UTC, wrager requested changes
Замечания

2017-03-17 09:57 UTC, wrager commented on lw5/lw5/lw5.cpp
> +		cout << "Command line parametres read error. Run app with /? to help.\n";
`parameters`

2017-03-17 10:06 UTC, onethousandsuns commented
Замечания исправлены

2017-03-21 05:12 UTC, wrager requested changes
Структура директорий не та

2017-03-21 05:46 UTC, onethousandsuns commented
Замечания исправлены

2017-04-04 06:13 UTC, wrager approved these changes

2017-04-04 06:14 UTC, wrager commented
Конфликты

2017-04-04 08:26 UTC, onethousandsuns commented
Конфликт зарезолвил

2017-04-25 05:09 UTC, merged