lw5 - Anikin
alexander-filimonov/pp pull request #8
Opened 2017-02-28 07:20 UTC by AniSkyWorker

2017-03-07 05:42 UTC, wrager requested changes
Замечания

2017-03-07 05:42 UTC, wrager commented on lw5/BatcherAlgorithm/BatcherAlgorithm.cpp
> +    return 0;
Так табы или пробелы? Давайте будем использовать 4 пробела

2017-03-07 05:42 UTC, wrager commented on lw5/BatcherAlgorithm/BatcherBaseCalculator.cpp
> +	size_t m = right * 2;
Из названия переменной непонятно, для чего она

2017-03-07 05:42 UTC, wrager commented on lw5/BatcherAlgorithm/CalculatorAgregator.cpp
> +	//for (auto const & num : vec)
Комментарии нужно удалить

2017-03-07 05:42 UTC, wrager commented on lw5/BatcherAlgorithm/ReadMe.txt
> +========================================================================
Readme тоже уберем

2017-03-07 05:42 UTC, wrager commented on lw5/BatcherAlgorithm/CalculatorAgregator.cpp
> +	//CoutArray("Unsorted", m_calc.GetResult());
Комментарий

2017-03-14 21:19 UTC, AniSkyWorker commented
исправил замечания

2017-03-21 05:14 UTC, wrager approved these changes

2017-03-21 05:15 UTC, wrager requested changes
Структура директорий не та

2017-03-24 19:32 UTC, AniSkyWorker commented
исправил

2017-04-04 06:15 UTC, merged