Lw5_glazyrin_vladimir_var_2
alexander-filimonov/pp pull request #9
Opened 2017-03-06 21:56 UTC by GlazyrinVladimir

2017-03-14 06:48 UTC, wrager commented on ConsoleApplication21/Sort.cpp
> +			for (int i = 0; i < 2; i++)
Зачем for?

2017-03-14 07:49 UTC, GlazyrinVladimir commented on ConsoleApplication21/Sort.cpp
> +			for (int i = 0; i < 2; i++)
Используется, чтобы разделить на два потока, без цикла работало не корректно - не было прироста в скорости

2017-03-21 05:16 UTC, wrager commented on ConsoleApplication21/Sort.cpp
> +			for (int i = 0; i < 2; i++)
Сделайте этот кусок без `for`

2017-04-25 05:11 UTC, wrager requested changes
Структура директорий неверная. См. задание

2017-05-16 06:18 UTC, wrager approved these changes

2017-05-16 06:19 UTC, merged